name: food
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted SDK range to be more flexible with newer Flutter versions
  # Your original: sdk: ^3.7.2 - Changed to be more compatible with latest Flutter

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2 # Consider updating to ^4.7.2 if you want the latest bug fixes, or flutter pub upgrade --major-versions
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  flutter_widget_from_html: ^0.16.0
  # rename: ^3.1.0 # MOVED TO DEV_DEPENDENCIES
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^11.0.0
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1

  http: ^1.4.0
  path: ^1.9.1
  # story: ^1.1.0 # REMOVED: Very old and potentially problematic package
  visibility_detector: ^0.4.0+2
  # onesignal_flutter: ^5.3.2 # REMOVED: User requested removal
  # firebase_analytics: ^11.4.5 # REMOVED: User requested removal
  url_launcher: ^6.3.1
  flutter_web_browser: ^0.17.3
  just_audio: ^0.9.46
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  quickalert: ^1.1.0
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4 # Correctly placed here
  rename: ^3.1.0 # Moved here as it's a development tool

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/database/FoodApp.db
    - assets/fonts/
    - assets/svg/
    - assets/png/
    - assets/icon/
    # If you had an assets/img folder and it's empty/unused, make sure it's NOT listed here
    # If it exists and has content, ensure you add it: - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ZainPeet
      fonts:
        - asset: assets/fonts/ZainPeet-Black.ttf
          weight: 900
        - asset: assets/fonts/ZainPeet-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZainPeet-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ZainPeet-Light.ttf
          weight: 300
        - asset: assets/fonts/ZainPeet-Regular.ttf
          weight: 400
      #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


# native splash screen configuration
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#323232"
  image: assets/icon/icon-logo1.png # Ensure this path is correct and image exists

  android: true
  ios: true
  web: false

  fullscreen: false
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/icon/icon-logo1.png # Ensure this path is correct and image exists
    color: "#ffffff"
    color_dark: "#323232"