// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3LTPt3Mk2-Sbe2B1E6zkS_G4_OdTOXM',
    appId: '1:330618682343:web:f1449323af242e8046db42',
    messagingSenderId: '330618682343',
    projectId: 'foodprophet-c0d91',
    authDomain: 'foodprophet-c0d91.firebaseapp.com',
    storageBucket: 'foodprophet-c0d91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBci9ezqywAb8iZeDOjbNW34t49EKEC-Pk',
    appId: '1:330618682343:android:78c01be8a63d204b46db42',
    messagingSenderId: '330618682343',
    projectId: 'foodprophet-c0d91',
    storageBucket: 'foodprophet-c0d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLcbQaDAA6pi0VXivpdRQOk1I5X_dlrE',
    appId: '1:330618682343:ios:4b599def1696760946db42',
    messagingSenderId: '330618682343',
    projectId: 'foodprophet-c0d91',
    storageBucket: 'foodprophet-c0d91.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfLcbQaDAA6pi0VXivpdRQOk1I5X_dlrE',
    appId: '1:330618682343:ios:4b599def1696760946db42',
    messagingSenderId: '330618682343',
    projectId: 'foodprophet-c0d91',
    storageBucket: 'foodprophet-c0d91.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs3LTPt3Mk2-Sbe2B1E6zkS_G4_OdTOXM',
    appId: '1:330618682343:web:63629a927628a4da46db42',
    messagingSenderId: '330618682343',
    projectId: 'foodprophet-c0d91',
    authDomain: 'foodprophet-c0d91.firebaseapp.com',
    storageBucket: 'foodprophet-c0d91.firebasestorage.app',
  );
}
